# Generated by Django 3.0.5 on 2022-05-12 20:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_notificationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
