# Generated by Django 3.0.5 on 2022-05-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20220512_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='seen',
            field=models.BooleanField(null=True),
        ),
    ]
