# Generated by Django 3.0.5 on 2022-05-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_notificationmodel_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='seen',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
